pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "terraform-0.11.8"
    }
    parameters {
        string(name: 'WORKSPACE', defaultValue: 'development', description:'worspace to use in Terraform')
    }
    environment {
        TF_HOME = tool('terraform-0.11.8')
        TF_IN_AUTOMATION = "true"
        PATH = "$TF_HOME:$PATH"
        DYNAMODB_STATELOCK = "vpcdemo10112018-tfstatelock"
        NETWORKING_BUCKET = "vpcdemo10112018-remotestate"
        NETWORKING_ACCESS_KEY = credentials('aws_access_key')
        NETWORKING_SECRET_KEY = credentials('aws_secret_key')
        ARM_SUBSCRIPTION_ID = credentials('arm_subscription')
        ARM_TENANT_ID = credentials('arm_tenant_id')
        VAR_FILE_NAME = "terraform.jenkins"
    }
    stages {
        stage('NetworkInit'){
            steps {
                dir('4-demo'){
                    sh 'terraform --version'
                    sh "terraform init -input=false \
                     --backend-config='dynamodb_table=$DYNAMODB_STATELOCK' --backend-config='bucket=$NETWORKING_BUCKET' \
                     --backend-config='access_key=$NETWORKING_ACCESS_KEY' --backend-config='secret_key=$NETWORKING_SECRET_KEY'"
                    sh "echo \$PWD"
                    sh "whoami"
                }
            }
        }
        stage('NetworkPlan'){
            steps {
                dir('4-demo'){
                    script {
                        try {
                           sh "terraform workspace new ${params.WORKSPACE}"
                        } catch (err) {
                            sh "terraform workspace select ${params.WORKSPACE}"
                        }
                        sh "terraform plan -var 'aws_access_key=$NETWORKING_ACCESS_KEY' -var 'aws_secret_key=$NETWORKING_SECRET_KEY' \
                        -var-file=$VAR_FILE_NAME -out terraform-networking.tfplan;echo \$? > status"
                        stash name: "terraform-networking-plan", includes: "terraform-networking.tfplan"
                    }
                }
            }
        }
        stage('NetworkApply'){
            steps {
                script{
                    def apply = false
                    try {
                        input message: 'confirm apply', ok: 'Apply Config'
                        apply = true
                    } catch (err) {
                        apply = false
                        dir('4-demo'){
                            sh "terraform destroy -var 'aws_access_key=$NETWORKING_ACCESS_KEY' \
                             -var-file=$VAR_FILE_NAME -var 'aws_secret_key=$NETWORKING_SECRET_KEY' -force"
                        }
                        currentBuild.result = 'UNSTABLE'
                    }
                    if(apply){
                        dir('4-demo'){
                            unstash "terraform-networking-plan"
                            sh 'terraform apply terraform-networking.tfplan'
                        }
                    }
                }
            }
        }
    }
}